### ISSUE TITLE
Lua error when performing AHDB scan

### ISSUE THREAD

**Issue by scyfar** [MarcLF/AuctionBuddy#1]
When running the AHDB scan the lua error below occurs rapidly but slows down over time. As seen by "Count" after almost 5k errors I stopped waiting for it to finish.
The lag presumably caused by these errors clears when the auction house window gets closed. 

When searching manually no lua error pops up.

**Auction House DataBase (AHDB)**
Version: `v0.14.00-classic`

**AuctionBuddy**
Version: `1.1.1 Beta (classic)`
Lua error:
```
Message: Interface\AddOns\AuctionBuddy\Modules\Items.lua:47: bad argument #1 to 'tostring' (value expected)
Time: Tue Sep 17 19:48:51 2019
Count: 4728
Stack: Interface\AddOns\AuctionBuddy\Modules\Items.lua:47: bad argument #1 to 'tostring' (value expected)
[C]: in function `tostring'
Interface\AddOns\AuctionBuddy\Modules\Items.lua:47: in function `CreateAuctionItemButtons'
Interface\AddOns\AuctionBuddy\AuctionBuddy.lua:97: in function `?'
...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119: in function <...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `Fire'
...dOns\AuctionBuddy\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...dOns\AuctionBuddy\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>
```

**Comment by MarcLF** [comment]
Sorry for the late reply, I don't know why I didn't see it, hopefully you had this error fixed in newer versions. Please feel free to open a new Issue if that's not the case. Thanks for the detailed report.
