### ISSUE TITLE
Addon misbehaves with Details addon enabled

### ISSUE THREAD

**Issue by TormDeltest** [MarcLF/AuctionBuddy#2]
Hi there, I noticed that the Addon misbehaves when I have addon Details enabled in Classic WoW. Everything works with Details disabled with no issues. Once I enable Details, then the AuctionBuddy stops showing in the AH interface and when I open Interface option, click on AuctionBuddy menu I see blank page. I tried to reinstall Details and AuctionBuddy (removing all Details and AuctionBuddy WTF files) but nothing changes. Can you please look into it? Cheers.

Details Enabled:
![obrazek](https://user-images.githubusercontent.com/18049853/94660267-bd43f780-0305-11eb-91df-71e3522381f0.png)

Details Disabled:
![obrazek](https://user-images.githubusercontent.com/18049853/94660396-e5335b00-0305-11eb-9cb6-e66a1fee3332.png)

**Comment by MarcLF** [comment]
Hey, thanks for the report. I think I've been able to find the cause and will be uploading a new version shortly.

**Comment by MarcLF** [comment]
New version has been uploaded, targeting this bug in particular, hopefully it will fix it.
