### ISSUE TITLE
Auction Buy/Sell windows always keep input focus

### ISSUE THREAD

**Issue by fleetcommand** [MarcLF/AuctionBuddy#3]
I have an issue where the "Search" field always keeps the input focus. Because of this, it is not possible to use the chat, for example, while the addon window is open.

Reproduction steps:

- Open AB sell or Buy
- Enter something to the Search field and press the "Enter" key to search or click "Search"
- As a next step, try clicking on the guild/general chat window and then press Enter to open the chat input line

The expected behavior would be to be able to chat. The actual behavior is that the chat input line does not activate, instead the addon repeats the search, even though we "clicked out" of the window. You can easily verify it if you click on the in-game chat, and then press Enter multiple times. You will see the "AuctionBuddy: Can't send queries to the auction house right now, try again in few seconds." message, even though we clicked out of the window already.

It would be great if the input focus would not be kept and the addon would not react to keypresses if we click outside the window/search field.

Please let me know in case of any questions or issues.

Thanks!

Szabolcs

edit: just to clarify, the above example was with the buy screen search field, but the price fields for the sell window are doing the same thing

**Comment by MarcLF** [comment]
Hi, sorry for the late response, I'll take a look into it and get back at you as soon as possible 👍

**Comment by MarcLF** [comment]
I've updated the addon (version 3.0.0 for Classic and 2.0.0 for BCC) so every time you press enter on any edit box it will clear it's focus so this shouldn't happen anymore.
Let me know if I can help you with anything else 👍
