### ISSUE TITLE
Addon doesn't work as of Patch 3.4.1 (Ulduar)

### ISSUE THREAD

**Issue by BoscoDomingo** [MarcLF/AuctionBuddy#5]
Hello, this addon no longer works on WoW WOTLK Classic since the new Ulduar patch. I can send the Lua Errors if needed to help debug it.

**Comment by MarcLF** [comment]
Hi, I've just released a new version of the addon on Curseforge that should fix all of the issues caused by the 3.4.1 patch.
But if you still experience any issue while using it, please, let me know! Thanks.
